version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - brecho-store-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      - brecho-store-net
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: xyz_one
      MYSQL_PASSWORD: xyz_pw
      MYSQL_ROOT_PASSWORD: xyz_Rpw
networks:
  brecho-store-net: