CREATE TABLE PEDIDO (
    ID INT NOT NULL AUTO_INCREMENT,
    CLIENTE_ID INT NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    STATUS ENUM('PENDENTE DE PRODUTO', 'PENDENTE DE PAGAMENTO') NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
) ENGINE=INNODB;
