CREATE TABLE ITENSDOPEDIDO (
   ID INT NOT NULL AUTO_INCREMENT,
   PEDIDO_ID INT NOT NULL,
   PRODUTO_ID INT NOT NULL,
   QUANTIDADE INT NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
   FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
)ENGINE=INNODB;