INSERT INTO basics.PRODUTO(NOME, preco) VALUES('CHINELO', 19.99);
INSERT INTO basics.PRODUTO(NOME, preco) VALUES('CAMISA', 56.00);
INSERT INTO basics.PRODUTO(NOME, preco) VALUES('CALÇA', 35.23);
INSERT INTO basics.PRODUTO(NOME, preco) VALUES('BERMUDA', 23.05);